export const baseBackendUrl = "http://localhost:5002/";
export const registerApiUrl = baseBackendUrl + "auth/register";
export const loginApiUrl = baseBackendUrl + "auth/login";
export const logoutApiUrl = baseBackendUrl + "auth/logout";
export const checkTokenApi = baseBackendUrl + "auth/check_token";
export const getAStudentUrl = baseBackendUrl + "student/profile/";
export const updateStudentUrl = baseBackendUrl + "student/profile/";
export const getAllGroupsUrl = baseBackendUrl + "groups/"
export const getAllStudentGroupsUrl = baseBackendUrl + "groups/get_groups_of_student"
export const getAllStudentsUrl = baseBackendUrl + "student/get_all_students"
export const createGroupUrl = baseBackendUrl + 'groups/create'
export const requestUrl = baseBackendUrl + 'group_request/'
export const deleteRequestUrl = baseBackendUrl + 'group_request/delete_student_request'
export const getStudentRequestUrl = baseBackendUrl + 'group_request/student_request'