export const baseBackendUrl = "http://localhost:5002/";
export const registerApiUrl = baseBackendUrl + "auth/register";
export const loginApiUrl = baseBackendUrl + "auth/login";
export const logoutApiUrl = baseBackendUrl + "auth/logout";
export const checkTokenApi = baseBackendUrl + "auth/check_token";
export const getAStudentUrl = baseBackendUrl + "student/profile/";
export const updateStudentUrl = baseBackendUrl + "student/profile/";
export const getAllGroupsUrl = baseBackendUrl + "groups/"
export const getAllStudentsUrl = baseBackendUrl + "student/get_all_students"
export const createGroupUrl = baseBackendUrl + 'groups/create'